# Generated by Django 5.0.2 on 2024-02-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marksadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CS', 'Computer science'), ('BCA', 'computer application'), ('FT', 'Food technology'), ('Physics', 'physics'), ('Maths', 'maths')], max_length=30)),
                ('mark', models.IntegerField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.student')),
            ],
        ),
    ]
